//
//  eflags.c
//  machineFriend
//
//  Created by Axis on 6/28/16.
//  Copyright © 2016 Axis. All rights reserved.
//


EFLAGS_SET_VALUE(rflags_map, "CF", 0)
EFLAGS_SET_VALUE(rflags_map, JUNCK_BIT, 0)
EFLAGS_SET_VALUE(rflags_map, "PF", 0)
EFLAGS_SET_VALUE(rflags_map, JUNCK_BIT, 0)
EFLAGS_SET_VALUE(rflags_map, "AF", 0)
EFLAGS_SET_VALUE(rflags_map, JUNCK_BIT, 0)
EFLAGS_SET_VALUE(rflags_map, "ZF", 0)
EFLAGS_SET_VALUE(rflags_map, "SF", 0)
EFLAGS_SET_VALUE(rflags_map, "TF", 0)
EFLAGS_SET_VALUE(rflags_map, "LF", 0)
EFLAGS_SET_VALUE(rflags_map, "DF", 0)
EFLAGS_SET_VALUE(rflags_map, "OF", 0)
EFLAGS_SET_VALUE(rflags_map, "LOPL", 0)
EFLAGS_SET_VALUE(rflags_map, "NT", 0)
EFLAGS_SET_VALUE(rflags_map, JUNCK_BIT, 0)
EFLAGS_SET_VALUE(rflags_map, "RF", 0)
EFLAGS_SET_VALUE(rflags_map, "VM", 0)
EFLAGS_SET_VALUE(rflags_map, "AC", 0)
EFLAGS_SET_VALUE(rflags_map, "VIF", 0)
EFLAGS_SET_VALUE(rflags_map, "VIP", 0)
EFLAGS_SET_VALUE(rflags_map, "ID", 0)